version: "3.8"

services:
  services.orchestrator:
    image: services.orchestrator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:80"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
