version: "3.8"

services:
  services.inventory:
    image: services.inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:80"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
