version: "3.8"

services:
  services.payment:
    image: services.payment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
