version: "3.8"

services:
  services.order:
    image: services.order
    container_name: services.order
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
