version: "3.7"

services:
  services.order:
    image: services.order
    container_name: services.order
    networks:
      - broker-kafka-network
    ports:
      - "5001:5001"
    build:
      context: .
      dockerfile: Dockerfile.order

  services.orchestrator:
    image: services.orchestrator
    container_name: services.orchestrator
    depends_on:
      - services.order
    ports:
      - "5002:5002"
    build:
      context: .
      dockerfile: Dockerfile.orchestrator

  services.inventory:
    image: services.inventory
    container_name: services.inventory
    networks:
      - services-inventory-network
    ports:
      - "5003:5003"
    build:
      context: ./Services.Inventory
      dockerfile: Dockerfile

  services.payment:
    image: services.payment
    container_name: services.payment
    networks:
      - services-payment-network
    ports:
      - "5004:5004"
    build:
      context: ./Services.Payment
      dockerfile: Dockerfile

networks:
  services-inventory-network:
    driver: bridge

  services-payment-network:
    driver: bridge
